### ISSUE TITLE
Uncaught TypeError: Cannot read property 'reset' of undefined

### ISSUE THREAD

**Issue by ghost** [learn-co/learn-ide-tree#40]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 2.4.0 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Home
**Thrown From**: [learn-ide-tree](https://github.com/learn-co/learn-ide-tree) package 1.0.22

### Stack Trace

Uncaught TypeError: Cannot read property 'reset' of undefined

```
At C:\ProgramData\RumaM\learn_ide\app-2.4.0\resources\app.asar\node_modules\nsync-fs\lib\connection.js:49

TypeError: Cannot read property 'reset' of undefined
    at Connection.module.exports.Connection.reset (/app.asar/node_modules/nsync-fs/lib/connection.js:49:23)
    at Nsync.resetConnection (/app.asar/node_modules/nsync-fs/lib/nsync-fs.js:86:28)
    at /app.asar/node_modules/learn-ide-tree/lib/nsync/initializer.js:157:18)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/app.asar/src/atom-environment.js:1164:28)
    at EventEmitter.outerCallback (/app.asar/src/application-delegate.js:320:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -0:59.5.0 pane:split-down-and-copy-active-item (div.item-views)
     -0:41.2.0 open-on-github:file (atom-pane.pane.active)
     -0:28.2.0 dev-live-reload:reload-all (atom-pane.pane.active)
     -0:24.4.0 learn-ide:reset-connection (atom-pane.pane.active)
```

### Non-Core Packages

```

```

**Comment by cyb3rn00b** [comment]
I have the same issue.

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 2.4.2 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [learn-ide-tree](https://github.com/learn-co/learn-ide-tree) package 1.0.22


### Stack Trace

Uncaught TypeError: Cannot read property 'reset' of undefined

```
At C:\Users\vinodh.swami\AppData\Local\learn_ide\app-2.4.2\resources\app.asar\node_modules\nsync-fs\lib\connection.js:49

TypeError: Cannot read property 'reset' of undefined
    at Connection.module.exports.Connection.reset (/app.asar/node_modules/nsync-fs/lib/connection.js:49:23)
    at Nsync.resetConnection (/app.asar/node_modules/nsync-fs/lib/nsync-fs.js:86:28)
    at /app.asar/node_modules/learn-ide-tree/lib/nsync/initializer.js:157:18)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/app.asar/src/atom-environment.js:1164:28)
    at EventEmitter.outerCallback (/app.asar/src/application-delegate.js:320:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -0:08.8.0 learn-ide:reset-connection (atom-pane.pane.active)
```

### Non-Core Packages

```

```

**Comment by jcpny1** [comment]
Same issue. IDE update seems to have failed. And now trying to restart, getting this error.

**Comment by lvalmoria** [comment]
I'm also getting this issue now post IDE update; update does not seem to have worked and getting this error when attempting to open/restart/etc.

**Comment by lisaychuang** [comment]
I am now getting the same error, stack trace:

```
TypeError: Cannot read property 'reset' of undefined
    at Connection.module.exports.Connection.reset (/Users/lhuang/.atom/packages/learn-ide-tree/node_modules/nsync-fs/lib/connection.js:49:23)
    at Nsync.resetConnection (/Users/lhuang/.atom/packages/learn-ide-tree/node_modules/nsync-fs/lib/nsync-fs.js:86:28)
    at atom-workspace.onResetConnection (/Users/lhuang/.atom/packages/learn-ide-tree/lib/nsync/initializer.coffee:121:9)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/private/var/folders/cs/0x04z7wx1h345_zdhbk78b280000gn/T/AppTranslocation/27AA6F4B-9136-4951-A20D-8A6CB609FCB9/d/Learn IDE.app/Contents/Resources/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/private/var/folders/cs/0x04z7wx1h345_zdhbk78b280000gn/T/AppTranslocation/27AA6F4B-9136-4951-A20D-8A6CB609FCB9/d/Learn IDE.app/Contents/Resources/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/private/var/folders/cs/0x04z7wx1h345_zdhbk78b280000gn/T/AppTranslocation/27AA6F4B-9136-4951-A20D-8A6CB609FCB9/d/Learn IDE.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/private/var/folders/cs/0x04z7wx1h345_zdhbk78b280000gn/T/AppTranslocation/27AA6F4B-9136-4951-A20D-8A6CB609FCB9/d/Learn IDE.app/Contents/Resources/app.asar/src/atom-environment.js:1164:28)
    at EventEmitter.outerCallback (/private/var/folders/cs/0x04z7wx1h345_zdhbk78b280000gn/T/AppTranslocation/27AA6F4B-9136-4951-A20D-8A6CB609FCB9/d/Learn IDE.app/Contents/Resources/app.asar/src/application-delegate.js:320:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

**Comment by amberjune** [comment]
Same problem today, first time I am experiencing this. It happened since I did the latest update to the IDE. Any suggestions on a fix?

[Before submitting, please enter steps to reproduce:]

1. Opened up Learn IDE and it shows no labs (tree) and no connection.
2. Did Packages > Learn IDE > Reconnect > then get this error and it won't connect.

**Learn IDE Package**: 2.5.2
**Learn IDE Core**: 2.4.2 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.5
**Thrown From**: [learn-ide-tree](https://github.com/learn-co/learn-ide-tree) package 1.0.23

### Stack Trace

Uncaught TypeError: Cannot read property 'reset' of undefined

```
At /Users/amber/.atom/packages/learn-ide-tree/node_modules/nsync-fs/lib/connection.js:49

TypeError: Cannot read property 'reset' of undefined
    at Connection.module.exports.Connection.reset (/packages/learn-ide-tree/node_modules/nsync-fs/lib/connection.js:49:23)
    at Nsync.resetConnection (/packages/learn-ide-tree/node_modules/nsync-fs/lib/nsync-fs.js:86:28)
    at /packages/learn-ide-tree/lib/nsync/initializer.coffee:121:9)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/app.asar/src/atom-environment.js:1164:28)
    at EventEmitter.outerCallback (/app.asar/src/application-delegate.js:320:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -1:54.6.0 learn-ide:reset-connection (atom-pane.pane.active)
     -1:13.7.0 learn-ide:update-check (atom-pane.pane.active)
  2x -0:59.1.0 learn-ide:log-in-out (atom-pane.pane.active)
     -0:13.4.0 learn-ide:reset-connection (textarea.xterm-helper-textarea)
```

### Non-Core Packages

```
learn-ide-notifications 0.66.5 
```

**Comment by pjlee87** [comment]
I was able to resolve this by uninstalling the `Learn IDE` and `Atom`, and then by deleting the `C/Users/Username/.atom` folder along with the `Learn IDE` and `Atom` folders from `C/Users/Username/AppData` - across `Local` and `Roaming`.  This is on Windows - the idea is to delete cached installation files before reinstallation in case you're on another OS.

**Comment by notnotdrew** [comment]
Thanks, all, for reporting. This bug is one we've been watching and hope to address in a future release.

While I'm not sure of the specifics, my recommendation would be to completely quit and restart the Learn IDE. I don't see anything here that would necessarily be addressed by a complete uninstall an reinstall.

**Comment by johnfewell** [comment]
I've completely quit and restarted the IDE many times, I also just uninstalled and reinstalled and the issue persists. 
EDIT: I can confirm that @pjlee87's solution works. Uninstall and then trash those folders, log in again. Thank you @pjlee87!

**Comment by pjlee87** [comment]
@johnfewell Yay - so glad to hear it worked! Thank you! Happy coding!

**Comment by nomorechickennuggets** [comment]
@drewprice people are paying (a lot) for these tools and when someone experiences a blocking issue as a result of broken tooling, your team's highest priority should be finding a fix or a workaround, or escalating to someone who can.  There are probably other people experiencing this that haven't posted up here or know to look here.  I'd advise anyone who was blocked by this to request a refund accounting for the time it took for you to become unblocked.  @aviflombaum I was a witness to one of your students struggling with this for over a day, being told to expect a follow-up within an hour and receiving no follow-up, and being left with a broken IDE on one of the few days that was reserved for study.  I'd recommend offering an escalation mechanism that can immediately address these kinds of issues and keep your paying students unblocked - and also encouraging your support staff to follow through on their commitments.

**Comment by aviflombaum** [comment]
@sb2059 I disagree but appreciate your comments. The tooling we provide like the IDE is to quick start people and make learning to code as easy as possible, but using a local environment is always possible and we are happy to help enrolled students. Students are paying to learn to code and change careers and there are a lot of things that go into that, from curriculum, to platform, to community, to tooling, to career services, to coaching, etc. To distill it to one thing and blame this as your roadblock is short sighted and incorrect. In terms of your feedback regarding escalation, we believe we are responsive and have a lot of methods to communicate with us that we support, GitHub issues on the IDE is generally not the best place. Anyway, thanks for the feedback, if you are dissatisfied I suggest speaking to us about a refund, though it looks like you are not an an enrolled student nor have ever been so I'm not sure what to tell you. Good luck.

**Comment by sb2059** [comment]
^ This, folks, is how *not* to provide customer service.  Best of luck.

**Comment by ghost** [comment]
I can confirm that @pjlee87 solution works on mac as well

**Comment by mckinney99** [comment]
Got this issue so I switched to a local environment as suggested. When I switched however, I couldn't figure out how to run the test in JS. I tried ask a question and downloading and updating node and npm to get the test running and after 2 hours now I'm giving up and reinstalling the learn IDE. I know it's not anyones fault by any means, but this is super frustrating when all I wanted to do today was code.

**Comment by aviflombaum** [comment]
Hi Eric,

I think dealing with errors and issues and environment problems is part of coding, it happens, don’t be frustrated, don’t blame your tools, sorry we couldn’t be more helpful with getting your local tests running, can you email support@learn.co about that and cc me avi@learn.co. Thanks.

**Comment by mckinney99** [comment]
Hey Avi, yes you are completely right. I just got frustrated being in the middle of the lab and all. Just discovered the browser version of the IDE and it’s the perfect solution for finishing labs when this issue does arise. Thank you for reaching out. I appreciate that.
